#!/bin/bash

VERSION=dev
if [[ "$SOURCE_BRANCH" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
  VERSION=${SOURCE_BRANCH:1}
fi

docker build \
  --build-arg VERSION=$VERSION \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .